### PR TITLE
Add Prettier to Github Actions for checking HTML/CSS/etc.

### PR DESCRIPTION
**Pull request by hummeltech**
* It will currently fail if errors are found, but continue if only `Code style issues` are found
* Applied to `openmaps_auth/static/css/splash_page.css`
* Fixed `SyntaxError` instances in HTML files:
  * `openmaps_auth/templates/index.html`
    * SyntaxError: Void elements do not have end tags "img"
  * `openmaps_auth/templates/login.html`
    * `<p class"mr2"></p>` => `<p class="mr2"></p>`
    * `<h1 class="form_title">Sign In:</h3>` => `<h1 class="form_title">Sign In:</h1>`
    * `<label class="form_label">Username:<label>` => `<label class="form_label">Username:</label>`
    * `<label class="form_label">Password:<label>` => `<label class="form_label">Password:</label>`
    * `<li class"form_input">{{ form.password }}</li>` => `<li class="form_input">{{ form.password }}</li>`
* Added `.gitignore` exclusion for `openmaps_auth/static`

### CODE REVIEW

**Comment by jbronn** [comment]
I don't think these changes caused this, but it made the password field overflow more apparent; Ideally we can fix this before merging:

image

**Comment by hummeltech** [comment]
> I don't think these changes caused this, but it made the password field overflow more apparent; Ideally we can fix this before merging:

Yeah, probably because there previously was no class assigned to the `li` input element.
https://github.com/radiant-maxar/openmaps-auth/pull/16/files#diff-4e3dd8d7587ccbec6c1e552a478d8a7c8f028d3c60b833e8f183b463fe27515aR49

Hmm, I'll have to look at it a bit more.

**Comment by hummeltech** [comment]
Alright @jbronn, that should fix the spacing issue, `width: 85%;` was not being applied to the `password` input type as it is for `text` types.
image

**Comment by hummeltech** [comment]
Everything else seems to look right as well:
image

**Review by jackgrossman18 — APPROVED** [review]

**Pull request merged**
